import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="rgb(254 249 195)" />
      </head>
      <body className={`${inter.className} overflow-hidden`}>{children}</body>
    </html>
  );
}
